title:            Legend(谭海燕)的专栏
description:      Someone to love. Something to hope. Something to do.
logo:             site-logo.png
disqus_shortname: legendsblog
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://www.fenesky.com
asset_url:        http://fenesky.aliapp.com 

# Owner/author information
owner:
  name:           Harlen Tan
  avatar:         bio-photo.jpg
  email:          hyman_tan@126.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         harlentan
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  weibo:          http://weibo.com/vernalday 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/110053076986281501134/posts

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         
google_ads_display: false
tb_ads_display: false
# Links to include in top navigation
# For external links add external: true
links:
  - title: 主页
    url: /
  - title: 博客
    url: /blog.html
  - title: 分类
    url: /tags.html
  - title: 相册
    url: /photos/index.html
  - title: 留言板
    url: /message.html
  - title: 关于
    url: /about.html
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter:  pygments
markdown:    redcarpet

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /blog/:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

#gallerytag:
#    dir: images/gallery
#    url: images/gallery
#    thumb_width: 250
#    thumb_height: 250
#    columns: 5
#

gallery:
  # path to the gallery
  dir: photos
  # title for gallery index
  title: "Photos"
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: "Photos: "
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "date_time"
  # sizes for thumbnails
  thumbnail_size:
    x: 200
    y: 200
  # custom configuration for individual gallery
  # best_image is image for the index page (defaults to last image)
  galleries:
    xiamen:
      best_image: 750b657bjw1e0pmtdjbibj.jpg
      catetory_tag: 厦门
      gallery_time: 2013年1月
    xitang:
      best_image: IMG_5975.jpg
      catetory_tag: 西塘
      gallery_time: 2012年12月
    snowman:
      best_image: 2013-01-04 12.51.42_x12.jpg
      catetory_tag: 雪人
      gallery_time: 2013年1月
    2013_honeys_birthday:
      best_image: 2013-03-13 18.31.09_x10.jpg
      catetory_tag: Someone's Birthday
      gallery_time: 2013年3月
    2013xian:
      best_image: 2013-03-09 15.38.37_x3.jpg
      catetory_tag: 西安
      gallery_time: 2013年3月

